version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PROD_API_DB_USER}
      POSTGRES_PASSWORD: ${PROD_API_DB_PASSWORD}
    ports:
      - ${PROD_API_DB_PORT}:${PROD_API_DB_PORT}
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "6660:6660"
    depends_on:
      - db