version: "3.9"
services:
  db:
    image: postgres
    ports:
      - ${PROD_API_DB_PORT}:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PROD_API_DB_USER}
      POSTGRES_PASSWORD: ${PROD_API_DB_PASSWORD}
  api:
    build: .
    command: "bin/rails server -p 3000"
    volumes:
      - .:/app
    ports:
      - "6660:3000"
    depends_on:
      - db