dev: &dev
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DEV_API_DB_USER'] %>
  password: <%= ENV.fetch('DEV_API_DB_PASSWORD') { '' } %>
  host: <%= ENV.fetch('DEV_API_DB_HOST') { 'localhost' } %>
  port: <% ENV.fetch('DEV_API_DB_PORT') { '5432' } %>

development:
  <<: *dev
  database: api_development

test:
  <<: *dev
  database: api_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PROD_API_DB_USER'] %>
  password: <%= ENV.fetch('PROD_API_DB_PASSWORD') { '' } %>
  host: <%= ENV.fetch('PROD_API_DB_HOST') { 'localhost' } %>
  port: <% ENV.fetch('PROD_API_DB_PORT') { '5432' } %>
  database: api_production
