default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: doadmin
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  host: <%= ENV['API_HOST'] %>
  port: 25060

development:
  <<: *default
  database: api_development

test:
  <<: *default
  database: api_test

production:
  <<: *default
  database: api_production
