default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_development
  username: doadmin
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  host: <%= ENV['API_HOST'] %>
  port: 25060

test:
  <<: *default
  database: api_test
  username: doadmin
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  host: <%= ENV['API_HOST'] %>
  port: 25060

production:
  <<: *default
  database: api_production
  username: doadmin
  password: <%= ENV['API_DATABASE_PASSWORD'] %>
  host: <%= ENV['API_HOST'] %>
  port: 25060
