local: &local
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['API_DB_USER'] %>
  password: <%= ENV['API_DB_PASSWORD'] %>
  host: <%= ENV['API_DB_HOST'] %>
  port: 5432

development:
  <<: *local
  database: api_development

test:
  <<: *local
  database: api_test

production:
  url: <%= ENV['DATABASE_URL'] %>
