local: &local
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DEV_API_DB_USER'] %>
  password: <%= ENV.fetch('DEV_API_DB_PASSWORD') { '' } %>
  host: <%= ENV.fetch('DEV_API_DB_HOST') { 'localhost' } %>
  port: 5432

development:
  <<: *local
  database: api_development

test:
  <<: *local
  database: api_test

production:
  adapter: postgresql
  url: <% ENV['DATABASE_URL'] %>
