name: CodeClimate

on:
  workflow_dispatch:
  push:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
              CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bin/rails test
          coverageLocations: ${{ github.workspace }}/coverage/coverage.json:simplecov
          debug: true
