name: CI

env:
  # Required app environment variables
  # https://github.com/TrailBuddies/api#environment-variables
  API_DB_USER: test
  API_DB_PASSWORD: test
  EMAIL: test@test.com
  PASSWORD: test1234
  # CLOUDINARY_SECRET: ${{ secrets.CLOUDINARY_SECRET }}
  # TOMTOM_API_KEY: ${{ secrets.TOMTOM_API_KEY }}

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ env.API_DB_USER }}
          POSTGRES_DB: ${{ env.API_DB_USER }}
          POSTGRES_PASSWORD: ${{ env.API_DB_PASSWORD }}
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      PASSPHRASE: test-${{ matrix.os }}-${{ github.run_id }}

    steps:

      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Rails Database
        run: RAILS_ENV='test' bin/keygen && bin/rails db:setup

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: bin/rails test
          coverageLocations: ${{ github.workspace }}/coverage/coverage.json:simplecov
          debug: true
