name: Docs

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  erd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: ts-graphviz/setup-graphviz@v1

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate ERD
        run: rake erd title="API Models Diagram" filetype=png filename=docs/ERD notation=bachman exclude="ActiveStorage::VariantRecord,ActiveStorage::Blob,ActiveStorage::Attachment"


      - name: Commit ERD
        run: |
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'Github Actions'
          git pull --commit
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m '[docs] Generate ERD'